# Generated by Django 5.1.5 on 2025-01-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='itens',
            field=models.JSONField(default=dict, help_text="Estrutura: {'product_id': {'name': str, 'title': str, 'price': int, 'stock': int, cover: str}}"),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
