# Generated by Django 5.1.5 on 2025-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0002_shopcart_itens_shopcart_total_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='itens',
            field=models.JSONField(default=dict, help_text="Estrutura: {'product_id': {'name': str, 'title': str, 'price': int, 'amount': int}}"),
        ),
    ]
