# Generated by Django 5.1.5 on 2025-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0006_alter_shopcart_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='itens',
            field=models.JSONField(default=dict, help_text="Estrutura: {'product_id': {'name': str, 'title': str, 'price': float, 'amount': int, 'cover': str}}"),
        ),
    ]
