# Generated by Django 5.1.5 on 2025-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatars/'),
        ),
    ]
